# Dependencies
kramdown:
  input: GFM
  syntax-highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Aryaman
tagline: 'My website'
description: 'This is my website and blog. I hope you like it!'
url: https://aryamanarora.github.io
baseurl: /

author:
  name: 'Aryaman Arora'
  url: https://github.com/aryamanarora

paginate: 5
paginate_path: "page:num"

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/aryamanarora/aryamanarora.github.io

# Gems
gems: [jekyll-paginate]
